[package]
name = "task-manager-system"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.13"
ctrlc = "3.4.5"
log = "0.4.22"
env_logger = "0.11.5"

[profile.release]
opt-level = 3
lto = "fat"
debug = false
strip = true