version: '3.9'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/20241005165245_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - '6370:6379'

volumes:
  db-data:
    driver: local