version: '3.9'


services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/20241005165245_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5444:5444"

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  db-data:
